


///////////////////////////////////////////////////////////////////////////
//NOTE: This file has been automatically generated by Vivado.
///////////////////////////////////////////////////////////////////////////
`timescale 1ps/1ps
package s_axis_vip_pkg;
import axi4stream_vip_pkg::*;
///////////////////////////////////////////////////////////////////////////
// These parameters are named after the component for use in your verification 
// environment.
///////////////////////////////////////////////////////////////////////////
      parameter s_axis_vip_VIP_INTERFACE_MODE     = 2;
      parameter s_axis_vip_VIP_SIGNAL_SET         = 8'b00010011;
      parameter s_axis_vip_VIP_DATA_WIDTH         = 8;
      parameter s_axis_vip_VIP_ID_WIDTH           = 0;
      parameter s_axis_vip_VIP_DEST_WIDTH         = 0;
      parameter s_axis_vip_VIP_USER_WIDTH         = 0;
      parameter s_axis_vip_VIP_USER_BITS_PER_BYTE = 0;
      parameter s_axis_vip_VIP_HAS_TREADY         = 1;
      parameter s_axis_vip_VIP_HAS_TSTRB          = 0;
      parameter s_axis_vip_VIP_HAS_TKEEP          = 0;
      parameter s_axis_vip_VIP_HAS_TLAST          = 1;
      parameter s_axis_vip_VIP_HAS_ACLKEN         = 0;
      parameter s_axis_vip_VIP_HAS_ARESETN        = 1;
///////////////////////////////////////////////////////////////////////////


typedef axi4stream_slv_agent #(s_axis_vip_VIP_SIGNAL_SET, 
                        s_axis_vip_VIP_DEST_WIDTH,
                        s_axis_vip_VIP_DATA_WIDTH,
                        s_axis_vip_VIP_ID_WIDTH,
                        s_axis_vip_VIP_USER_WIDTH, 
                        s_axis_vip_VIP_USER_BITS_PER_BYTE,
                        s_axis_vip_VIP_HAS_ARESETN) s_axis_vip_slv_t;
      
///////////////////////////////////////////////////////////////////////////
// How to start the verification component
///////////////////////////////////////////////////////////////////////////
//      s_axis_vip_slv_t  s_axis_vip_slv;
//      initial begin : START_s_axis_vip_SLAVE
//        s_axis_vip_slv = new("s_axis_vip_slv", `s_axis_vip_PATH_TO_INTERFACE);
//        s_axis_vip_slv.start_slave();
//      end

endpackage : s_axis_vip_pkg
